services:
  school-news-bot:
    build: .
    container_name: school_news_bot
    restart: unless-stopped
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN} 
      - TZ=Europe/Moscow
    volumes:
      - ./data:/app/data